- hosts: network
  gather_facts: no
  connection: network_cli
  tasks:
    - include_role:
        name: cisco_nxos_backup
      vars:
        network_backup_repository: 'git@github.com:repo/backups.git'
